name: 'Terragrunt plan output'
description: 'Setup terragrunt and init'
inputs:
  working_dir:
    description: 'Terragrunt working directory'
    required: true
  github_token:
    description: 'github token'
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Terragrunt init'
      id: init
      working-directory: ${{ inputs.working_dir }}
      run: terragrunt init --terragrunt-non-interactive
    - name: 'Terragrunt plan'
      id: plan
      working-directory: ${{ inputs.working_dir }}
      run: terragrunt run-all plan --terragrunt-non-interactive
    - name: 'Plan output comment'
      id: plan
      uses: actions/github-script@0.9.0
      env:
        PLAN: "terragrunt\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ inputs.github_token }}
        script: |
           const output = `
           #### Terragrunt Initialization \`${{ steps.init.outcome }}\`
           #### Terragrunt Plan \`${{ steps.plan.outcome }}\`
           <details><summary>Show Plan</summary>

           \`\`\` terraform
           ${process.env.PLAN}
           \`\`\`

           </details>
           Pusher: @${{ github.actor }}`;

           github.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: output
           })
