name: 'Terragrunt plan output'
description: 'Setup terragrunt and init'
inputs:
  working_dir:
    description: 'Terragrunt working directory'
    required: true
outputs:
  init_outcome:
    description: 'Terragrunt init outcome'
  plan_outcome:
    description: 'Terragrunt plan outcome'
  plan_output:
    description: 'Terragrunt plan output'
runs:
  using: "composite"
  steps:
    - name: 'Terragrunt init'
      id: init
      working-directory: ${{ inputs.working_dir }}
      run: terragrunt init --terragrunt-non-interactive
      shell: bash
    - name: 'Terragrunt init outcome'
      run: echo "::set-output name=init_outcome::${{ steps.init.outcome }}"
      shell: bash
    - name: 'Terragrunt plan'
      id: plan
      working-directory: ${{ inputs.working_dir }}
      run: terragrunt run-all plan --terragrunt-non-interactive
      shell: bash
    - name: 'Terragrunt plan outcome'
      run: echo "::set-output name=plan_outcome::${{ steps.plan.outcome }}"
      shell: bash
    - name: 'Terragrunt plan output'
      run: echo "::set-output name=plan_output::${{ steps.plan.outputs.stdout }}"
      shell: bash
