# adapted from: https://github.com/sjevs/cloudformation-s3-static-website-with-cloudfront-and-route-53/blob/master/s3-static-website-with-cloudfront-and-route-53.yaml
# to create: aws cloudformation deploy --stack-name=software-downloads-bucket --parameter-overrides FullDomainName=software.curibio.com --template-file=software-downloads-bucket.yaml
# aws cloudformation package --template-file software-downloads-bucket.yaml --output-template-file software-downloads-bucket.packaged.yaml --s3-bucket cf-templates-curibioprod-us-east-1
# aws cloudformation deploy --stack-name=software-downloads-bucket --template-file=software-downloads-bucket.packaged.yaml


AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an S3 bucket configured for hosting a static website
Resources:
  TheBucket:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: ../../templates/s3/public-website-bucket.yaml
        Parameters:
          FullDomainName: software.curibio.com