# adapted from: https://github.com/sjevs/cloudformation-s3-static-website-with-cloudfront-and-route-53/blob/master/s3-static-website-with-cloudfront-and-route-53.yaml
# to create: aws cloudformation deploy --stack-name=cloud-formation-templates-bucket-us-east-1 --parameter-overrides TheBucketName=cf-templates-us-east-1-curi-bio-prod --template-file=generic-bucket.yaml

AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an S3 bucket. If HostStaticWebsite is set to True, then the bucket must be public and not encrypted and any parameters to restrict public access or apply encryption will be overridden
Parameters:
  TheBucketName:
    Type: String
    Description: The name for the bucket
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
  CostCenterTagValue:
    Type: String
    Description: The cost center that this bucket should be charged to
  UseDeafaltServerSideEncryption:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  AllowServerAccessLogDelivery:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  EnableServerAccessLogging:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  HostStaticWebsite:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  BlockPublicAcls:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  BlockPublicPolicy:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  IgnorePublicAcls:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  RestrictPublicBuckets:
    Type: String
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be true/false
  VersioningStatus:
    Type: String
    Default: Suspended
    AllowedValues:
      - Enabled
      - Suspended
    ConstraintDescription: Must be Enabled/Suspended
  ExportedBucketNamePrefix:
    Type: String
    Description: Used for naming the exported bucket name. Typically the name of the Root Stack. Leave blank to not export the name
    Default: ""

Conditions:
  ExportBucketName:
    Fn::Not:
      - Fn::Equals:
        - Ref: ExportedBucketNamePrefix
        - ""
  ConditionAllowServerAccessLogDelivery:
    Fn::Equals:
      - Ref: AllowServerAccessLogDelivery
      - true
  ConditionEnableServerAccessLogging:
    Fn::Equals:
      - Ref: EnableServerAccessLogging
      - true
  ConditionHostStaticWebsite:
    Fn::Equals:
      - Ref: HostStaticWebsite
      - true
  ConditionUseDeafaltServerSideEncryption:
    Fn::Equals:
      - Ref: UseDeafaltServerSideEncryption
      - true

Resources:
  GenericBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: user:Cost Center
          Value:
            Ref: CostCenterTagValue
      BucketName:
        Ref: "TheBucketName"
      VersioningConfiguration:
        Status:
          Ref: "VersioningStatus"
      BucketEncryption:
        Fn::If:
          - ConditionHostStaticWebsite
          - Ref: AWS::NoValue
          - Fn::If:
            - ConditionUseDeafaltServerSideEncryption
            - ServerSideEncryptionConfiguration:
                - ServerSideEncryptionByDefault:
                    SSEAlgorithm: "AES256"
            - Ref: "AWS::NoValue"


      PublicAccessBlockConfiguration:
        BlockPublicAcls:
          Fn::If:
          - ConditionHostStaticWebsite
          - "false"
          - Ref: "BlockPublicAcls"
        BlockPublicPolicy:
          Fn::If:
          - ConditionHostStaticWebsite
          - "false"
          - Ref: "BlockPublicPolicy"
        IgnorePublicAcls:
          Fn::If:
          - ConditionHostStaticWebsite
          - "false"
          - Ref: "IgnorePublicAcls"
        RestrictPublicBuckets:
          Fn::If:
          - ConditionHostStaticWebsite
          - "false"
          - Ref: "RestrictPublicBuckets"
      AccessControl:
        Fn::If:
          - ConditionAllowServerAccessLogDelivery
          - "LogDeliveryWrite"
          - Fn::If:
            - ConditionHostStaticWebsite
            - "PublicRead"
            - Ref: AWS::NoValue
      WebsiteConfiguration:
        Fn::If:
          - ConditionHostStaticWebsite
          - IndexDocument: index.html
            ErrorDocument: 404.html
          - Ref: AWS::NoValue

      LoggingConfiguration:
        Fn::If:
          - ConditionEnableServerAccessLogging
          - DestinationBucketName:
              Fn::ImportValue:
                Fn::Join:
                  - "-"
                  - - "s3-server-logs-bucket"
                    - Ref: "AWS::Region"
                    - "-bucket-name"
            LogFilePrefix:
              Fn::Join:
                - ""
                - - Ref: TheBucketName
                  - "/"
          - Ref: AWS::NoValue
    DeletionPolicy: Delete
  WebsiteBucketPolicy:
    Condition: ConditionHostStaticWebsite
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "GenericBucket"
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "GenericBucket"
                  - "/*"


Outputs:
  BucketName:
    Value:
      Ref: "GenericBucket"
    Description: Name of S3 bucket

  ExportedBucketName:
    Value:
      Ref: "GenericBucket"
    Description: Exported Name of S3 bucket # Eli (8/11/20) was unable to figure out a way to conditionally export the name as part of the same output, so had to duplicate it
    Condition: ExportBucketName
    Export:
      Name:
        Fn::Join:
          - "--"
          - - Ref: ExportedBucketNamePrefix
            - "bucket-name"

