# adapted from: https://github.com/sjevs/cloudformation-s3-static-website-with-cloudfront-and-route-53/blob/master/s3-static-website-with-cloudfront-and-route-53.yaml
# to create: aws cloudformation deploy --stack-name=s3-server-logs-bucket-us-east-1 --parameter-overrides RootStackName=s3-server-logs-bucket-us-east-1 AllowServerAccessLogDelivery=yes EnableServerAccessLogging=no TheBucketName=s3-server-logs-curibioprod-us-east-1 --template-file=generic-bucket-with-exported-name.yaml

AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a bucket that has its name exported for use in cross-stack references
Parameters:
  TheBucketName:
    Type: String
    Description: The name for the bucket
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
  RootStackName:
    Type: String
    Description: Used for naming the exported bucket name
  AllowServerAccessLogDelivery:
    Type: String
    Default: no
    AllowedValues:
    - yes
    - no
    ConstraintDescription: Must be yes/no
  EnableServerAccessLogging:
    Type: String
    Default: yes
    AllowedValues:
    - yes
    - no
    ConstraintDescription: Must be yes/no

Resources:
  TheBucket:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: generic-bucket.yaml
        Parameters:
          TheBucketName:
            Ref: TheBucketName
          EnableServerAccessLogging:
            Ref: EnableServerAccessLogging
          AllowServerAccessLogDelivery:
            Ref: AllowServerAccessLogDelivery

Outputs:
  BucketName:
    Description: The name of the bucket
    Value:
      Fn::GetAtt:
        TheBucket.Outputs.BucketName
    Export:
      Name:
        Fn::Join:
          - "--"
          - - Ref: RootStackName
            - "bucket-name"
