# adapted from: https://github.com/sjevs/cloudformation-s3-static-website-with-cloudfront-and-route-53/blob/master/s3-static-website-with-cloudfront-and-route-53.yaml
# to create: aws cloudformation deploy --stack-name=software-downloads-bucket --parameter-overrides FullDomainName=software.curibio.com --template-file=software-downloads-bucket.yaml

AWSTemplateFormatVersion: "2010-09-09"
Description: Creates an S3 bucket configured for hosting a static website
Parameters:
  FullDomainName:
    Type: String
    Description: The full domain name e.g. www.curibio.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name.
Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: "FullDomainName"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
    DeletionPolicy: Delete
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: "WebsiteBucket"
      PolicyDocument:
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: "WebsiteBucket"
                  - "/*"
Outputs:
  BucketName:
    Value:
      Ref: "WebsiteBucket"
    Description: Name of S3 bucket to hold website content
  FullDomain:
    Value:
      Ref: "FullDomainName"
    Description: Full DomainName
