"""initial schema

Revision ID: 10c965144f38
Revises:
Create Date: 2021-11-22 12:27:02.501351
Revision by: Luci Pak

"""

# revision identifiers, used by Alembic.
revision = "10c965144f38"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
