# to create: aws cloudformation deploy --stack-name=iam-groups --template-file=groups.yaml --capabilities CAPABILITY_NAMED_IAM

AWSTemplateFormatVersion: "2010-09-09"
Description: Creates IAM Groups and their inline policies
Parameters:
  CustomerDownloadsBucketName:
    Type: String
    Description: The name for the bucket
    Default: downloads.curibio.com
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:
  HandlesCustomerFacingDocumentsGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "handles-customer-facing-documents"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObjectAcl
                  - s3:GetBucketObjectLockConfiguration
                  - s3:GetObjectVersionTagging
                  - s3:GetBucketVersioning"
                  - s3:GetBucketAcl
                  - s3:GetObjectTorrent
                  - s3:GetBucketCORS
                  - s3:GetBucketLocation
                  - s3:GetObjectVersion
                  - s3:GetBucketRequestPayment
                  - s3:GetObjectTagging
                  - s3:GetMetricsConfiguration
                  - s3:GetBucketPublicAccessBlock
                  - s3:ListBucket
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketPolicy
                  - s3:GetEncryptionConfiguration
                  - s3:DeleteObjectVersion
                  - s3:GetBucketLogging
                  - s3:ListBucketVersions
                  - s3:GetAnalyticsConfiguration
                  - s3:GetObjectVersionForReplication
                  - s3:GetLifecycleConfiguration
                  - s3:ListBucketByTags
                  - s3:GetInventoryConfiguration
                  - s3:GetBucketTagging
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersionTagging
                  - s3:GetObjectAcl
                  - s3:GetBucketObjectLockConfiguration
                  - s3:GetObjectVersionAcl
                  - s3:PutObjectTagging
                  - s3:DeleteObject
                  - s3:DeleteObjectTagging
                  - s3:GetBucketPolicyStatus
                  - s3:GetObjectRetention
                  - s3:GetBucketWebsite
                  - s3:DeleteObjectVersionTagging
                  - s3:GetObjectLegalHold
                  - s3:GetBucketNotification
                  - s3:GetReplicationConfiguration
                Effect: Allow
                Resource:
                  - Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: "CustomerDownloadsBucketName"
                      - "/*"
                  - Fn::Join:
                    - ""
                    - - "arn:aws:s3:::"
                      - Ref: "CustomerDownloadsBucketName"
          PolicyName: "read-write-access-to-downloads-bucket"
