# aws cloudformation package --template-file build-artifacts-bucket.yaml --output-template-file build-artifacts-bucket.packaged.yaml --s3-bucket cf-templates--us-east-1--curi-bio--prod
# aws cloudformation deploy --stack-name=build-artifacts-bucket --template-file=build-artifacts-bucket.packaged.yaml --parameter-overrides Stage=prod

AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a bucket to host build artifacts
Parameters:
  Stage:
    Type: String
    Description: The stage for deployment
    AllowedValues:
    - test
    - modl
    - prod
    ConstraintDescription: Must be a valid stage name (test, modl, or prod).

Resources:
  TheBucket:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: ../../templates/s3/generic-bucket.yaml
        Parameters:
          ExportedBucketNamePrefix:
            Ref: "AWS::StackName"
          TheBucketName:
            Fn::Join:
              - "--"
              - - "build-artifacts"
                - Ref: "AWS::Region"
                - Fn::ImportValue: "BucketNameUniquifier"
                - Ref: Stage

Outputs:
  BuildArtifactBucketName:
    Description: The name of the bucket
    Value:
      Fn::GetAtt:
        TheBucket.Outputs.BucketName
