name: 'Terragrunt plan'
description: 'Run terragrunt plan'
outputs:
  plan-output:
    description: 'Terragrunt plan output'
    value: ${{ steps.terragrunt_plan.outputs.stdout }}
runs:
  using: "composite"
  steps:
    - id: terragrunt_plan
      run: terragrunt run-all plan --terragrunt-non-interactive -no-color
      shell: bash

