# aws cloudformation package --template-file build-resources.yaml --output-template-file build-resources.packaged.yaml --s3-bucket cf-templates-curi-bio-prod-us-east-1
# aws cloudformation deploy --stack-name=build-resources --template-file=build-resources.packaged.yaml --parameter-overrides Stage=prod

AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a bucket for caches and other resources. Also relevant SSM Parameters (for now generic strings are created and then manually need to be changed to SecureStrings...hopefully soon AWS will figure out how to create SecureStrings via CloudFormation)
Parameters:
  Stage:
    Type: String
    Description: The stage for deployment
    AllowedValues:
    - test
    - modl
    - prod
    ConstraintDescription: Must be a valid stage name (test, modl, or prod).
  CostCenterTagValue:
    Type: String
    Default: "Software Overhead"


Resources:
  BuildResourcesBucket:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: ../templates/s3/generic-bucket.yaml
        Parameters:
          CostCenterTagValue:
            Ref: CostCenterTagValue
          ExportedBucketNamePrefix:
            Fn::Join:
              - "--"
              - - Ref: "AWS::StackName"
                - "build-resources"
          TheBucketName:
            Fn::Join:
              - "--"
              - - "build-resources"
                - Ref: "AWS::Region"
                - Fn::ImportValue: "BucketNameUniquifier"
                - Ref: Stage
  BuildArtifactsBucket:
      Type: AWS::CloudFormation::Stack
      Properties:
        TemplateURL: ../templates/s3/generic-bucket.yaml
        Parameters:
          CostCenterTagValue:
            Ref: CostCenterTagValue
          ExportedBucketNamePrefix:
            Fn::Join:
              - "--"
              - - Ref: "AWS::StackName"
                - "build-artifacts"
          TheBucketName:
            Fn::Join:
              - "--"
              - - "build-artifacts"
                - Ref: "AWS::Region"
                - Fn::ImportValue: "BucketNameUniquifier"
                - Ref: Stage
  VcnNotarizationPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Password to perform VCN notarization / code signing
      Tags:
        "user:Cost Center":
          Ref: CostCenterTagValue
      Name:
        Fn::Join:
          - "/"
          - - "/CodeBuild/general"
            - "vcn-password"
      Type: "String"
      Value: "must be edited manually in the Systems Manager"
  VcnNotarizationNotarizationPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Extra password needed to perform VCN notarization / code signing
      Tags:
        "user:Cost Center":
          Ref: CostCenterTagValue
      Name:
        Fn::Join:
          - "/"
          - - "/CodeBuild/general"
            - "vcn-notarization-password"
      Type: "String"
      Value: "must be edited manually in the Systems Manager"
  VcnNotarizationUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: Username to perform VCN notarization / code signing
      Tags:
        "user:Cost Center":
          Ref: CostCenterTagValue
      Name:
        Fn::Join:
          - "/"
          - - "/CodeBuild/general"
            - "vcn-username"
      Type: "String"
      Value: "must be edited manually in the Systems Manager"
