name: 'Terraform PR Close'
on:
  pull_request:
    types: [closed]
    branches-ignore:
    - 'main'

jobs:
  terraform:
    name: 'Terraform PR Close'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_user_id: ${{ github.actor }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Setup Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: 'Terraform setup'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: 'Terraform destroy PR environment'
      run: python ./.github/scripts/tf-deploy-env.py --workspace "${{ github.actor }}-${{ github.event.pull_request.number }}" --destroy

    - name: 'Terraform apply modl environment'
      if: github.event.pull_request.merged == true
      run: python ./.github/scripts/tf-deploy-env.py --workspace modl --apply

