name: 'Open/Update PR into Prod'
on:
  workflow_dispatch:
    inputs:
      randomlyseed:
        description: 'Pytest Randomly Seed'
        required: false
        default: ''
  pull_request:
    branches-ignore:
    - 'development'

jobs:
  terraform:
    name: 'Terraform PR Open'
    runs-on: "ubuntu-20.04"

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_user_id: ${{ github.actor }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Setup Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
        python -m venv venv

    - name: Activate virtual environment (Linux/MacOS)
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: . venv/bin/activate

    - name: Display Pip Version and confirm environment empty
      run: |
        pip -V
        pip freeze

    - name: Install Dev Dependencies
      run: pip install -r requirements-dev.txt

    - name: Log full installed packages
      run: pip freeze

    - name: 'Terraform setup'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.7

    - name: 'Create Environment'
      id: tfenv
      run: python ./.github/scripts/tf-deploy-env.py --workspace prod --no-color

    - name: 'Terraform plan dev output'
      uses: actions/github-script@v3.1
      env:
        PLAN: "terraform\n${{ steps.tfenv.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
          <details><summary>Show Plan</summary>

          \`\`\` terraform
          ${process.env.PLAN}
          \`\`\`

          </details>

          Pusher: @${{ github.actor }}`;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Run Tests with randomly generated seed
      if: github.event.inputs.randomlyseed == ''
      run: pytest -xsvv tests/ --tf-workspace-name modl

    - name: Run Tests with supplied pytest-randomly seed
      if: github.event.inputs.randomlyseed != ''
      run: pytest -xsvv tests/ --tf-workspace-name modl --randomly-seed=${{ github.event.inputs.randomlyseed }}
