name: 'Terraform Plan'
on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./infra/environments/test
    shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: "ubuntu-20.04"

    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.7

      - name: 'Terragrunt Setup'
        run: |
          sudo wget -q -O /bin/terragrunt "https://github.com/gruntwork-io/terragrunt/releases/download/v0.28.7/terragrunt_linux_amd64"
          sudo chmod +x /bin/terragrunt
          terragrunt -v

      - name: 'Terragrunt Init'
        run: terragrunt init --terragrunt-non-interactive

      - name: 'Terraform Plan'
        run: terragrunt plan --terragrunt-non-interactive -no-color


